# Generated by Django 3.2.2 on 2024-04-18 16:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('inventoried', models.BooleanField(default=True, verbose_name='¿Es inventariado?')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Cirugia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(null=True, verbose_name='Motivo')),
                ('fecha', models.DateField(verbose_name='Fecha de la cirugía')),
                ('hora', models.TimeField(verbose_name='Hora de la cirugía')),
                ('firma_propietario', models.FileField(upload_to='firmas/', verbose_name='Firma del propietario para el consentimiento de la cirugia')),
            ],
            options={
                'verbose_name': 'Cirugía',
                'verbose_name_plural': 'Cirugías',
                'ordering': ['-fecha', '-hora'],
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.TextField(verbose_name='Asunto')),
                ('descripcion', models.TextField(null=True, verbose_name='Descripción')),
                ('fecha_cita', models.DateField(verbose_name='Fecha de la cita')),
                ('hora_cita', models.TimeField(verbose_name='Hora de la cita')),
                ('estado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=10, unique=True, verbose_name='Teléfono')),
                ('birthdate', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de nacimiento')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='Dirección')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('ruc', models.CharField(max_length=13, verbose_name='Ruc')),
                ('address', models.CharField(max_length=200, verbose_name='Dirección')),
                ('mobile', models.CharField(max_length=10, verbose_name='Teléfono celular')),
                ('phone', models.CharField(max_length=9, verbose_name='Teléfono convencional')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('website', models.CharField(max_length=250, verbose_name='Página web')),
                ('desc', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, null=True, upload_to='company/%Y/%m/%d', verbose_name='Logo')),
                ('igv', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Igv')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['-id'],
                'permissions': (('view_company', 'Can view Company'),),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='CtasCollect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(default=datetime.datetime.now)),
                ('end_date', models.DateField(default=datetime.datetime.now)),
                ('debt', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('saldo', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('state', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cuenta por cobrar',
                'verbose_name_plural': 'Cuentas por cobrar',
                'ordering': ['-id'],
                'permissions': (('view_ctascollect', 'Can view Cuentas por cobrar'), ('add_ctascollect', 'Can add Cuentas por cobrar'), ('delete_ctascollect', 'Can delete Cuentas por cobrar')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_diagnostico', models.DateField(default=datetime.date.today, verbose_name='Fecha del diagnóstico')),
                ('temperatura', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Temperatura del paciente')),
                ('mucosa', models.CharField(max_length=50, null=True, verbose_name='Estado de las mucosas')),
                ('motivo_consulta', models.TextField(null=True, verbose_name='Motivo de consulta')),
                ('sintomas', models.TextField(null=True, verbose_name='Síntomas del paciente')),
                ('examenes_realizados', models.TextField(null=True, verbose_name='Exámenes realizados')),
                ('observaciones_veterinario', models.TextField(null=True, verbose_name='Observaciones del veterinario')),
                ('diagnostico_provicional', models.TextField(max_length=300, null=True, verbose_name='Diagnóstico Provicional')),
                ('condicion_llegada', models.TextField(max_length=50, null=True, verbose_name='Condición de llegada')),
            ],
        ),
        migrations.CreateModel(
            name='Hospitalizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de ingreso')),
                ('fecha_salida', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de salida')),
                ('medicinas_aplicadas', models.CharField(max_length=400, verbose_name='Medicinas aplicadas')),
                ('motivo', models.CharField(max_length=150, verbose_name='Motivo')),
                ('antecedentes', models.TextField(verbose_name='Antecedentes')),
                ('tratamiento', models.CharField(max_length=200, verbose_name='Tratamiento')),
                ('internado', models.BooleanField(default=True, verbose_name='Internado')),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(max_length=150)),
                ('mobile', models.CharField(max_length=9, unique=True, verbose_name='Teléfono')),
                ('codigo_medico', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código del medico veterinario')),
                ('certificado', models.FileField(upload_to='documentos/', verbose_name='Certificado')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=150, verbose_name='Identificación de la mascota: FORMATO (SVT-1)')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la mascota')),
                ('fecha_nacimiento', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de nacimiento')),
                ('sexo', models.CharField(choices=[('sin especificar', 'Sin especificar'), ('macho', 'Macho'), ('hembra', 'Hembra')], default='sin especificar', max_length=150)),
                ('tamanio', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Tamaño')),
                ('raza', models.CharField(blank=True, max_length=150, null=True)),
                ('declaracion_jurada', models.FileField(upload_to='documentos/', verbose_name='Declaracion jurada del propietario')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Caracteristicas del paciente')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentsCtaCollect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de registro')),
                ('desc', models.CharField(blank=True, max_length=500, null=True, verbose_name='Detalles')),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Pago Cuenta por cobrar',
                'verbose_name_plural': 'Pagos Cuentas por cobrar',
                'ordering': ['-id'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Precio de Compra')),
                ('pvp', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Precio de Venta')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product/%Y/%m/%d', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamentos', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_condition', models.CharField(choices=[('contado', 'Contado'), ('credito', 'Credito')], default='contado', max_length=50)),
                ('payment_method', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta_debito_credito', 'Tarjeta de Debito / Credito'), ('efectivo_tarjeta', 'Efectivo y Tarjeta')], default='efectivo', max_length=50)),
                ('type_voucher', models.CharField(choices=[('ticket', 'Ticket'), ('factura', 'Factura')], default='ticket', max_length=50)),
                ('date_joined', models.DateField(default=datetime.datetime.now)),
                ('end_credit', models.DateField(default=datetime.datetime.now)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('dscto', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('total_dscto', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('igv', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('total_igv', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cash', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('change', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('card_number', models.CharField(blank=True, max_length=30, null=True)),
                ('titular', models.CharField(blank=True, max_length=30, null=True)),
                ('amount_debited', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pos.client')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-id'],
                'permissions': (('view_sale', 'Can view Ventas'), ('add_sale', 'Can add Ventas'), ('delete_sale', 'Can delete Ventas')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='TipoMascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_mascota', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='SaleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('dscto', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('total_dscto', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.sale')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalle de Ventas',
                'ordering': ['-id'],
                'default_permissions': (),
            },
        ),
    ]
