# Generated by Django 3.2.2 on 2024-04-18 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receta',
            name='mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.paciente', verbose_name='Mascota'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.category', verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='paymentsctacollect',
            name='ctascollect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.ctascollect'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.client'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='tipo_mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.tipomascota'),
        ),
        migrations.AddField(
            model_name='medico',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hospitalizacion',
            name='mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.paciente', verbose_name='Mascota'),
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.medico', verbose_name='Médico veterinario'),
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos', to='pos.paciente'),
        ),
        migrations.AddField(
            model_name='ctascollect',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.sale'),
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cita',
            name='mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.paciente'),
        ),
        migrations.AddField(
            model_name='cita',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.medico'),
        ),
        migrations.AddField(
            model_name='cita',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.client'),
        ),
        migrations.AddField(
            model_name='cirugia',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.client', verbose_name='Propietario'),
        ),
        migrations.AddField(
            model_name='cirugia',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.medico', verbose_name='Médico veterinario'),
        ),
        migrations.AddField(
            model_name='cirugia',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.paciente', verbose_name='Mascota'),
        ),
    ]
