# Generated by Django 3.2.2 on 2024-04-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='unidad_edad',
            field=models.CharField(choices=[('años', 'Años'), ('meses', 'Meses')], default='años', max_length=20),
        ),
    ]
