# Generated by Django 3.2.2 on 2024-04-19 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostico',
            name='esterilizado',
            field=models.BooleanField(default=False, verbose_name='Esterilizado'),
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='frecuencia_cardiaca',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Frecuencia Cardíaca'),
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='frecuencia_respiratoria',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Frecuencia Respiratoria'),
        ),
    ]
