# Generated by Django 3.2.2 on 2024-04-16 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_receta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cirugia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de la cirugía')),
                ('hora', models.TimeField(verbose_name='Hora de la cirugía')),
                ('firma_propietario', models.ImageField(upload_to='firmas/', verbose_name='Firma del propietario')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.client', verbose_name='Propietario')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.medico', verbose_name='Médico veterinario')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.paciente', verbose_name='Mascota')),
            ],
            options={
                'verbose_name': 'Cirugía',
                'verbose_name_plural': 'Cirugías',
                'ordering': ['-fecha', '-hora'],
            },
        ),
    ]
