# Generated by Django 3.2.2 on 2024-04-05 15:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pos', '0002_remove_product_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_mascota', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.IntegerField(default=0)),
                ('nombre', models.CharField(max_length=150)),
                ('fecha_nacimiento', models.DateField(default=datetime.datetime(2024, 4, 5, 15, 28, 41, 340588, tzinfo=utc))),
                ('sexo', models.CharField(default='No especificado', max_length=150)),
                ('tamanio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('raza', models.CharField(blank=True, max_length=150)),
                ('edad', models.IntegerField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('descipcion', models.TextField(blank=True)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.client')),
                ('tipo_mascota', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pos.tipomascota')),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.TextField()),
                ('descipcion', models.TextField()),
                ('fecha_cita', models.DateField()),
                ('hora_cita', models.TimeField()),
                ('mascota', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pos.paciente')),
                ('medico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pos.medico')),
                ('propietario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pos.client')),
            ],
        ),
    ]
