# Generated by Django 3.2.2 on 2024-04-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_paciente_unidad_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='unidad_edad',
            field=models.CharField(choices=[('año(s)', 'Año(s)'), ('meses(s)', 'Mes(es)')], default='años', max_length=20),
        ),
    ]
