# Generated by Django 3.2.2 on 2024-04-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='certificado',
            field=models.FileField(upload_to='documentos/', verbose_name='Certificado'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='declaracion_jurada',
            field=models.FileField(upload_to='documentos/', verbose_name='Declaracion jurada del propietario'),
        ),
    ]
