# Generated by Django 3.2.2 on 2024-04-09 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_alter_paciente_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='tipo_mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.tipomascota'),
        ),
    ]
