# Generated by Django 3.2.2 on 2024-04-05 16:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_cita_medico_paciente_tipomascota'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.datetime(2024, 4, 5, 16, 11, 5, 956433, tzinfo=utc)),
        ),
    ]
