# Generated by Django 3.2.2 on 2024-04-09 18:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_alter_paciente_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='hospitalizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de ingreso')),
                ('fecha_salida', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de salida')),
                ('medicinas_aplicadas', models.CharField(max_length=400, verbose_name='Medicinas aplicadas')),
                ('motivo', models.CharField(max_length=150, verbose_name='Motivo')),
                ('antecedentes', models.TextField(verbose_name='Antecedentes')),
                ('tratamiento', models.CharField(max_length=200, verbose_name='Antecedentes')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.paciente', verbose_name='Mascota')),
            ],
        ),
    ]
