# Generated by Django 3.2.2 on 2024-04-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_hospitalizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalizacion',
            name='tratamiento',
            field=models.CharField(max_length=200, verbose_name='Tratamiento'),
        ),
    ]
