# Generated by Django 3.2.2 on 2024-04-06 02:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_auto_20240405_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='descipcion',
            new_name='descripcion',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.datetime(2024, 4, 6, 2, 1, 19, 586980, tzinfo=utc)),
        ),
    ]
