# Generated by Django 3.2.2 on 2024-04-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_auto_20240419_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='alergias',
            field=models.TextField(null=True, verbose_name='Alergias del Paciente'),
        ),
    ]
