# Generated by Django 3.2.2 on 2024-04-17 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_cirugia'),
        ('pos', '0004_auto_20240415_1214'),
    ]

    operations = [
    ]
