# Generated by Django 3.2.2 on 2024-04-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_paciente_alergias'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='foto',
            field=models.ImageField(null=True, upload_to='fotos_pacientes/', verbose_name='Foto del Paciente'),
        ),
    ]
