# Generated by Django 3.2.2 on 2024-04-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_alter_hospitalizacion_tratamiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalizacion',
            name='internado',
            field=models.BooleanField(default=False),
        ),
    ]
