# Generated by Django 3.2.2 on 2024-04-06 04:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_auto_20240405_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='identificacion',
            field=models.IntegerField(verbose_name='Identificación de la mascota'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Nombre de la mascota'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='raza',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(choices=[('sin especificar', 'Sin especificar'), ('hembra', 'Hembra'), ('macho', 'Macho')], default='sin especificar', max_length=150),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='tamanio',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Tamaño'),
        ),
    ]
