# Generated by Django 3.2.2 on 2024-04-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_auto_20240417_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnostico',
            name='examenes_fisicos',
        ),
        migrations.RemoveField(
            model_name='diagnostico',
            name='observacion_veterinario',
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='condicion_llegada',
            field=models.CharField(max_length=50, null=True, verbose_name='Condición de llegada'),
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='examenes_realizados',
            field=models.TextField(null=True, verbose_name='Exámenes realizados'),
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='motivo_consulta',
            field=models.TextField(null=True, verbose_name='Motivo de consulta'),
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='mucosa',
            field=models.CharField(max_length=50, null=True, verbose_name='Estado de las mucosas'),
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='observaciones_veterinario',
            field=models.TextField(null=True, verbose_name='Observaciones del veterinario'),
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='temperatura',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Temperatura del paciente'),
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='diagnostico_provicional',
            field=models.TextField(max_length=300, null=True, verbose_name='Diagnóstico Provicional'),
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='sintomas',
            field=models.TextField(null=True, verbose_name='Síntomas del paciente'),
        ),
    ]
