# Generated by Django 3.2.2 on 2024-04-19 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_auto_20240419_1358'),
        ('pos', '0006_paciente_foto'),
    ]

    operations = [
    ]
