# Generated by Django 3.2.2 on 2024-04-08 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_auto_20240405_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='mobile',
            field=models.CharField(default=2, max_length=10, unique=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.datetime(2024, 4, 8, 12, 16, 53, 775055)),
        ),
    ]
