# Generated by Django 3.2.2 on 2024-04-08 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_auto_20240408_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='mobile',
            field=models.CharField(max_length=10, unique=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.datetime(2024, 4, 8, 14, 0, 52, 799389)),
        ),
    ]
