# Generated by Django 3.2.2 on 2024-04-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_auto_20240417_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostico',
            name='condicion_llegada',
            field=models.TextField(max_length=50, null=True, verbose_name='Condición de llegada'),
        ),
    ]
