# Generated by Django 3.2.2 on 2024-04-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0008_alter_diagnostico_condicion_llegada'),
    ]

    operations = [
        migrations.AddField(
            model_name='cirugia',
            name='motivo',
            field=models.TextField(null=True, verbose_name='Motivo'),
        ),
        migrations.AlterField(
            model_name='cirugia',
            name='firma_propietario',
            field=models.FileField(upload_to='firmas/', verbose_name='Firma del propietario para el consentimiento de la cirugia'),
        ),
    ]
