# Generated by Django 3.2.2 on 2024-04-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0008_auto_20240422_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='alergias_bolean',
            field=models.BooleanField(default=False, verbose_name='¿El paciente tiene alguna alergia?'),
        ),
    ]
