# Generated by Django 3.2.2 on 2024-04-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0009_paciente_alergias_bolean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='declaracion_jurada',
            field=models.FileField(blank=True, null=True, upload_to='documentos/', verbose_name='Declaracion jurada del propietario'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_pacientes/', verbose_name='Foto del Paciente'),
        ),
    ]
