# Generated by Django 3.2.2 on 2024-04-24 13:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0010_auto_20240424_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='fecha_nacimiento_value',
            field=models.DateField(default=datetime.datetime.now, null=True, verbose_name='Fecha de nacimiento'),
        ),
    ]
