# Generated by Django 3.2.2 on 2024-04-25 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0011_alter_paciente_fecha_nacimiento_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalles_banio', models.TextField(blank=True, null=True, verbose_name='Detalles del baño')),
                ('hora_ingreso', models.TimeField(blank=True, null=True, verbose_name='Hora de ingreso')),
                ('hora_salida', models.TimeField(blank=True, null=True, verbose_name='Hora de salida')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.client', verbose_name='Cliente')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.paciente', verbose_name='Mascota')),
            ],
            options={
                'verbose_name': 'Baño',
                'verbose_name_plural': 'Baños',
            },
        ),
    ]
